"use client";

import { useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { useForm, useWatch } from "react-hook-form";
import { ArrowLeft, Award, Briefcase, Building2, CalendarDays, CheckCircle2, Loader2, Save } from "lucide-react";
import { toast } from "sonner";
import useAdminStore from "@/lib/store/adminStore";

const defaults = { role: "", company: "", duration: "", metrics: "", achievements: "" };
export default function ExperienceEditor({ experienceIndex = null }) {
  const router = useRouter();
  const { resumeData, fetchResume, updateResume } = useAdminStore();
  const [loading, setLoading] = useState(experienceIndex !== null);
  const { register, control, reset, handleSubmit, formState: { isSubmitting, errors } } = useForm({ defaultValues: defaults });
  const role = useWatch({ control, name: "role" }) || "Your professional role";
  const company = useWatch({ control, name: "company" }) || "Organization";
  const duration = useWatch({ control, name: "duration" }) || "Duration";
  const metrics = useWatch({ control, name: "metrics" }) || "Core achievement";

  useEffect(() => { Promise.resolve(fetchResume()).finally(() => setLoading(false)); }, [fetchResume]);
  useEffect(() => { if (experienceIndex === null || !resumeData) return; const item = resumeData.experience?.[Number(experienceIndex)]; const timer = window.setTimeout(() => { if (item) reset({ ...item, achievements: Array.isArray(item.achievements) ? item.achievements.join("\n") : item.achievements || "" }); setLoading(false); }, 0); return () => window.clearTimeout(timer); }, [experienceIndex, resumeData, reset]);

  const submit = async (data) => { const toastId = toast.loading(experienceIndex === null ? "Adding experience..." : "Updating experience..."); try { const item = { ...data, achievements: String(data.achievements || "").split(/\r?\n/).map((value) => value.trim()).filter(Boolean) }; const current = [...(resumeData?.experience || [])]; if (experienceIndex === null) current.push(item); else current[Number(experienceIndex)] = { ...current[Number(experienceIndex)], ...item }; const result = await updateResume({ ...(resumeData || {}), experience: current }); if (!result?.success) throw new Error("Could not save experience"); toast.success(experienceIndex === null ? "Experience added" : "Experience updated", { id: toastId }); router.push("/admin/resume"); router.refresh(); } catch (error) { toast.error(error.message, { id: toastId }); } };
  if (loading) return <div className="grid min-h-[65vh] place-items-center"><Loader2 className="size-7 animate-spin text-blue-300" /></div>;

  return <form onSubmit={handleSubmit(submit)} className="mx-auto max-w-5xl pb-24"><header className="mb-6 flex flex-col justify-between gap-4 rounded-[22px] border border-white/[0.09] bg-[#0d1727] p-4 sm:flex-row sm:items-center sm:px-6"><div className="flex items-center gap-3"><button type="button" onClick={() => router.push("/admin/resume")} className="grid size-10 place-items-center rounded-xl border border-white/[0.08] text-slate-500 hover:text-white"><ArrowLeft className="size-4" /></button><div><p className="text-[9px] font-bold uppercase tracking-[.2em] text-blue-300">Career editor</p><h1 className="mt-1 text-lg font-semibold text-white">{experienceIndex === null ? "Add work experience" : "Edit work experience"}</h1></div></div><button disabled={isSubmitting} className="inline-flex h-11 items-center justify-center gap-2 rounded-xl bg-blue-300 px-5 text-xs font-bold text-slate-950 hover:bg-blue-200 disabled:opacity-50">{isSubmitting ? <Loader2 className="size-4 animate-spin" /> : <Save className="size-4" />}Save experience</button></header><div className="grid items-start gap-6 lg:grid-cols-[minmax(0,1fr)_340px]"><section className="overflow-hidden rounded-[24px] border border-white/[0.08] bg-[#0d1727]"><Header icon={Briefcase} eyebrow="Experience details" title="Role and achievements" /><div className="grid gap-5 p-5 sm:p-7 md:grid-cols-2"><Field label="Role title" error={errors.role?.message}><input {...register("role", { required: "Role is required" })} /></Field><Field label="Organization" error={errors.company?.message}><input {...register("company", { required: "Organization is required" })} /></Field><Field label="Duration" error={errors.duration?.message}><input {...register("duration", { required: "Duration is required" })} placeholder="2023 — Present" /></Field><Field label="Core achievement" error={errors.metrics?.message}><input {...register("metrics", { required: "Achievement is required" })} /></Field><div className="md:col-span-2"><Field label="Achievements"><textarea {...register("achievements")} rows={8} placeholder="One achievement per line" /></Field></div></div></section><aside className="overflow-hidden rounded-[24px] border border-white/[0.08] bg-[#0d1727] lg:sticky lg:top-28"><Header icon={Award} eyebrow="Live preview" title="Timeline entry" /><div className="p-5"><div className="rounded-2xl border border-blue-400/15 bg-blue-400/[0.035] p-5"><p className="text-[9px] font-bold uppercase tracking-wider text-blue-300">{company}</p><h2 className="mt-2 text-base font-semibold text-white">{role}</h2><div className="mt-4 flex items-center gap-2 text-xs text-slate-500"><CalendarDays className="size-3.5" />{duration}</div><div className="mt-4 flex gap-2 border-t border-white/[0.06] pt-4 text-xs leading-5 text-slate-400"><CheckCircle2 className="mt-0.5 size-4 shrink-0 text-emerald-300" />{metrics}</div></div></div></aside></div></form>;
}
function Header({ icon: Icon, eyebrow, title }) { return <div className="flex items-center gap-3 border-b border-white/[0.07] px-5 py-4"><span className="grid size-9 place-items-center rounded-xl bg-blue-400/10 text-blue-300"><Icon className="size-4" /></span><div><p className="text-[9px] font-bold uppercase tracking-[.18em] text-slate-600">{eyebrow}</p><h2 className="mt-1 text-sm font-semibold text-slate-100">{title}</h2></div></div>; }
function Field({ label, error, children }) { return <label className="block"><span className="mb-2 block text-[9px] font-bold uppercase tracking-[.16em] text-slate-500">{label}</span><div className="[&_input]:w-full [&_input]:rounded-xl [&_input]:border [&_input]:border-white/[0.08] [&_input]:bg-slate-950/35 [&_input]:p-3.5 [&_input]:text-sm [&_input]:outline-none [&_textarea]:w-full [&_textarea]:resize-y [&_textarea]:rounded-xl [&_textarea]:border [&_textarea]:border-white/[0.08] [&_textarea]:bg-slate-950/35 [&_textarea]:p-4 [&_textarea]:text-sm [&_textarea]:leading-6 [&_textarea]:outline-none">{children}</div>{error && <p className="mt-2 text-[10px] text-rose-300">{error}</p>}</label>; }
