"use client";

import { useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { useFieldArray, useForm } from "react-hook-form";
import { ArrowLeft, Award, Briefcase, GraduationCap, Layers3, Link2, Loader2, Plus, Save, Trash2, User } from "lucide-react";
import { toast } from "sonner";
import useAdminStore from "@/lib/store/adminStore";

const defaults = { name: "", role: "", tagline: "", aboutSummary: "", contact: [], stats: [], education: [], skillCategories: [], notableProjects: [] };
export default function ResumeEditor({ mode = "profile" }) {
  const router = useRouter();
  const { resumeData, fetchResume, updateResume } = useAdminStore();
  const [loading, setLoading] = useState(true);
  const { register, control, reset, handleSubmit, formState: { isSubmitting, errors } } = useForm({ defaultValues: defaults });
  useEffect(() => { Promise.resolve(fetchResume()).finally(() => setLoading(false)); }, [fetchResume]);
  useEffect(() => { if (!resumeData) return; const timer = window.setTimeout(() => { reset({ ...defaults, ...resumeData, aboutSummary: resumeData.aboutSummary || resumeData.about || "", skillCategories: (resumeData.skillCategories || resumeData.skills || []).map((item) => ({ ...item, items: text(item.items) })), notableProjects: (resumeData.notableProjects || resumeData.projects || []).map((item) => ({ ...item, tech: text(item.tech) })) }); setLoading(false); }, 0); return () => window.clearTimeout(timer); }, [resumeData, reset]);
  const submit = async (data) => { const toastId = toast.loading("Saving resume..."); try { const payload = mode === "profile" ? { ...(resumeData || {}), name: data.name, role: data.role, tagline: data.tagline, aboutSummary: data.aboutSummary, about: data.aboutSummary } : { ...(resumeData || {}), contact: data.contact || [], stats: data.stats || [], education: data.education || [], skillCategories: (data.skillCategories || []).map((item) => ({ ...item, items: split(item.items) })), notableProjects: (data.notableProjects || []).map((item) => ({ ...item, tech: split(item.tech) })) }; const result = await updateResume(payload); if (!result?.success) throw new Error("Could not save resume"); toast.success("Resume updated", { id: toastId }); router.push("/admin/resume"); router.refresh(); } catch (error) { toast.error(error.message, { id: toastId }); } };
  if (loading) return <div className="grid min-h-[65vh] place-items-center"><Loader2 className="size-7 animate-spin text-blue-300" /></div>;
  return <form onSubmit={handleSubmit(submit)} className="mx-auto max-w-6xl pb-24"><header className="mb-6 flex flex-col justify-between gap-4 rounded-[22px] border border-white/[0.09] bg-[#0d1727] p-4 sm:flex-row sm:items-center sm:px-6"><div className="flex items-center gap-3"><button type="button" onClick={() => router.push("/admin/resume")} className="grid size-10 place-items-center rounded-xl border border-white/[0.08] text-slate-500 hover:text-white"><ArrowLeft className="size-4" /></button><div><p className="text-[9px] font-bold uppercase tracking-[.2em] text-blue-300">Resume editor</p><h1 className="mt-1 text-lg font-semibold text-white">{mode === "profile" ? "Professional profile" : "Resume sections"}</h1></div></div><button disabled={isSubmitting} className="inline-flex h-11 items-center justify-center gap-2 rounded-xl bg-blue-300 px-5 text-xs font-bold text-slate-950 hover:bg-blue-200 disabled:opacity-50">{isSubmitting ? <Loader2 className="size-4 animate-spin" /> : <Save className="size-4" />}Save resume</button></header>{mode === "profile" ? <ProfileEditor register={register} errors={errors} /> : <SectionsEditor register={register} control={control} />}</form>;
}

function ProfileEditor({ register, errors }) { return <div className="grid items-start gap-6 lg:grid-cols-[minmax(0,1fr)_320px]"><Section icon={User} eyebrow="Profile core" title="Professional identity"><div className="grid gap-5 md:grid-cols-2"><Field label="Full name" error={errors.name?.message}><input {...register("name", { required: "Name is required" })} /></Field><Field label="Professional role" error={errors.role?.message}><input {...register("role", { required: "Role is required" })} /></Field><div className="md:col-span-2"><Field label="Professional tagline"><input {...register("tagline")} /></Field></div><div className="md:col-span-2"><Field label="Career summary"><textarea {...register("aboutSummary")} rows={10} /></Field></div></div></Section><aside className="rounded-[24px] border border-blue-400/15 bg-blue-400/[0.035] p-6"><User className="size-6 text-blue-300" /><h2 className="mt-5 text-lg font-semibold text-white">Keep it concise</h2><p className="mt-3 text-xs leading-6 text-slate-500">Your name, role, tagline and career summary appear at the top of the public Resume page. Use a clear role and a summary focused on outcomes.</p></aside></div>; }
function SectionsEditor({ register, control }) { return <div className="space-y-6"><Section icon={Link2} eyebrow="Contact" title="Contact information"><Repeater control={control} register={register} name="contact" title="Contact item" fields={["icon", "text"]} /></Section><Section icon={Award} eyebrow="Statistics" title="Professional metrics"><Repeater control={control} register={register} name="stats" title="Statistic" fields={["label", "value", "icon"]} /></Section><Section icon={GraduationCap} eyebrow="Education" title="Academic background"><Repeater control={control} register={register} name="education" title="Education record" fields={["degree", "institution", "duration"]} /></Section><Section icon={Layers3} eyebrow="Expertise" title="Skill categories"><Repeater control={control} register={register} name="skillCategories" title="Skill category" fields={["category", "items"]} hints={{ items: "Comma separated skills" }} /></Section><Section icon={Briefcase} eyebrow="Portfolio" title="Notable projects"><Repeater control={control} register={register} name="notableProjects" title="Project" fields={["name", "tech", "outcome"]} hints={{ tech: "Comma separated technologies" }} /></Section></div>; }
function Section({ icon: Icon, eyebrow, title, children }) { return <section className="overflow-hidden rounded-[24px] border border-white/[0.08] bg-[#0d1727]"><div className="flex items-center gap-3 border-b border-white/[0.07] px-5 py-4 sm:px-6"><span className="grid size-9 place-items-center rounded-xl bg-blue-400/10 text-blue-300"><Icon className="size-4" /></span><div><p className="text-[9px] font-bold uppercase tracking-[.18em] text-slate-600">{eyebrow}</p><h2 className="mt-1 text-sm font-semibold text-slate-100">{title}</h2></div></div><div className="p-5 sm:p-6">{children}</div></section>; }
function Repeater({ control, register, name, title, fields, hints = {} }) { const list = useFieldArray({ control, name }); return <div><div className="mb-4 flex items-center justify-between"><p className="text-xs text-slate-500">{list.fields.length} entries</p><button type="button" onClick={() => list.append(Object.fromEntries(fields.map((field) => [field, ""])))} className="inline-flex items-center gap-2 rounded-lg border border-blue-400/20 px-3 py-2 text-[9px] font-bold uppercase tracking-wider text-blue-300"><Plus className="size-3" />Add {title}</button></div><div className="grid gap-3 md:grid-cols-2">{list.fields.map((item, index) => <div key={item.id} className="rounded-2xl border border-white/[0.07] bg-white/[0.02] p-4"><div className="mb-3 flex items-center justify-between"><span className="text-[9px] font-bold uppercase tracking-wider text-slate-600">{title} {index + 1}</span><button type="button" onClick={() => list.remove(index)} className="grid size-8 place-items-center rounded-lg text-slate-700 hover:bg-rose-400/10 hover:text-rose-300"><Trash2 className="size-3.5" /></button></div><div className="space-y-3">{fields.map((field) => <Field key={field} label={fieldName(field)}><input {...register(`${name}.${index}.${field}`)} placeholder={hints[field] || ""} /></Field>)}</div></div>)}</div>{list.fields.length === 0 && <div className="rounded-xl border border-dashed border-white/[0.08] py-10 text-center text-xs text-slate-600">No entries added yet.</div>}</div>; }
function Field({ label, error, children }) { return <label className="block"><span className="mb-2 block text-[9px] font-bold uppercase tracking-[.16em] text-slate-500">{label}</span><div className="[&_input]:w-full [&_input]:rounded-xl [&_input]:border [&_input]:border-white/[0.08] [&_input]:bg-slate-950/35 [&_input]:p-3.5 [&_input]:text-sm [&_input]:outline-none [&_textarea]:w-full [&_textarea]:resize-y [&_textarea]:rounded-xl [&_textarea]:border [&_textarea]:border-white/[0.08] [&_textarea]:bg-slate-950/35 [&_textarea]:p-4 [&_textarea]:text-sm [&_textarea]:leading-6 [&_textarea]:outline-none">{children}</div>{error && <p className="mt-2 text-[10px] text-rose-300">{error}</p>}</label>; }
const split = (value) => String(value || "").split(",").map((item) => item.trim()).filter(Boolean); const text = (value) => Array.isArray(value) ? value.join(", ") : value || ""; const fieldName = (value) => value.replace(/([A-Z])/g, " $1").replace(/^./, (character) => character.toUpperCase());
